debug = true
logLevel = "DEBUG"

[accessLog]
  filePath = "access.log"

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  #compress = true
  address = ":443"
    [entryPoints.https.tls]

[acme]
email = "martinklepsch@googlemail.com"
storage = "/data/acme.json"
entryPoint = "https"
onHostRule = true
[acme.tlsChallenge]

[[acme.domains]]
main = "traefik.cljdoc.org"

[api]
[ping]

[consulCatalog]
prefix = "traefik"
constraints = ["tag==cljdoc"]
watch = true

#TODO strip trailing /
