debug = true
logLevel = "DEBUG"

[accessLog]
  filePath = "traefik-access.log"

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  compress = true
  address = ":443"
    [entryPoints.https.tls]

[acme]
email = "martinklepsch@googlemail.com"
storage = "acme.json"
entryPoint = "https"
onHostRule = true
[acme.tlsChallenge]

[[acme.domains]]
main = "traefik.cljdoc.org"

[file]
watch = true

[backends]
  [backends.cljdoc]
    [backends.cljdoc.healthcheck]
    path = "/ping"
    interval = "10s"
    [backends.cljdoc.servers.server1]
    url = "http://127.0.0.1:8001"
    [backends.cljdoc.servers.server2]
    url = "http://127.0.0.1:8002"
    [backends.cljdoc.servers.server3]
    url = "http://127.0.0.1:8003"

[frontends]
  [frontends.cljdoc]
  backend = "cljdoc"
  entryPoints = ["https"]
  [frontends.cljdoc.routes.main]
    rule = "Host:traefik.cljdoc.org"